name: keynginx
version: '1.0.0'
summary: SSL-enabled Nginx automation with Docker
description: |
  KeyNginx automates SSL certificate generation, Nginx configuration,
  and Docker container management for secure web development.

grade: stable
confinement: strict
base: core22

parts:
  keynginx:
    plugin: go
    source: .
    build-snaps: [go/1.21/stable]
    build-environment:
      - CGO_ENABLED: "0"

apps:
  keynginx:
    command: bin/keynginx
    plugs:
      - network
      - docker